language: java
env:
  global:
    - JENKINSCI_USERNAME=kallekula
    - ENCRYPTION_LABEL: "8ded143b9563"
    - secure: "V3nNF5p8ycitAxu49T0TTY19r5URcYZAxc/dcJmiDOlmPA1ftX8igCpi6FJRjwWe9PvaOsOTp8zoBqekqs6++wHmOws67uisy9fED13IBDuOIXzT9SoTU1SpDN22iUrhrf7BWB2kxuFtUn5PJUw+dl3Qrpcb+4reOs35h9K+oxE="
jdk:
- oraclejdk7
script:
  env
after_success:
  - "if [[ -n $TRAVIS_TAG ]]; then ./release.sh; fi"
